import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RalewayFont } from "./Font/Font";
import Dock from "./layout/Dock";
import Footer from "./layout/Footer";
import SmoothScroll from "./components/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Aztate | A Real Estate Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${RalewayFont.variable} antialiased`}
      >
        <SmoothScroll>
          {children}
          <Footer />
          <Dock />
        </SmoothScroll>
      </body>
    </html>
  );
}
